############
#
#   project: MariaDB with phpMyAdmin
#   owner:   Deryl Schmid
#   creation date: 28.04.2021
#   last change: 30.04.2021
#   
############


version: "2"
services:
  db:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=radio
      volumes:
          - ./database:/var/lib/mysql
      networks:
        v_net:
            ipv4_address: 192.168.60.100

networks:
    v_net:
        ipam:
            driver: default
            config:
                - subnet: 192.168.60.0/24